// ============================================================
// THE POLITICAL RANT — STORY FEED
// ============================================================
// HOW TO ADD A NEW STORY:
// Copy one block below, paste it at the TOP of the STORIES array
// (newest first), and fill in your own details. That's it —
// save this file, refresh the site, done. No build step needed.
//
// FIELDS:
//   headline   - your own short, punchy framing (1 line). Do NOT
//                copy-paste the source's exact headline text —
//                write your own take on what happened.
//   blurb      - 1-2 sentences of context, in your own words.
//   source     - name of the outlet you're linking to
//   url        - the actual article URL on the source's site
//   category   - one of: "national", "states", "economy",
//                "courts", "defence", "world", "opinion"
//   lean       - the outlet's general leaning: "left", "right", "center", "state-run"
//   date       - "YYYY-MM-DD"
// ============================================================

const STORIES = [

  // ── 3 JULY 2026 ──────────────────────────────────────────

  {
    headline: "Supreme Court calls AI-hallucinated case citations in tribunal orders 'catastrophic'",
    blurb: "The court struck down an NCLT ruling that relied on non-existent legal precedents generated by an AI tool, warning that fabricated material in judicial decisions strikes at the rule of law itself.",
    source: "The Hindu",
    url: "https://www.thehindu.com",
    category: "courts",
    lean: "center",
    date: "2026-07-03"
  },
  {
    headline: "GST collections hit ₹1.95 lakh crore in June — but critics say the numbers flatter to deceive",
    blurb: "A 13.9% year-on-year rise sounds impressive, but analysts point out the jump is largely driven by imported inflation and a weaker rupee, not actual growth in domestic economic activity.",
    source: "Mint",
    url: "https://www.livemint.com",
    category: "economy",
    lean: "center",
    date: "2026-07-03"
  },
  {
    headline: "Delhi riots accused spent years behind bars without trial — Supreme Court says 'bail is not punishment'",
    blurb: "An editorial flags the growing paradox: UAPA's stringent bail conditions mean accused persons are effectively imprisoned before being convicted, with the Supreme Court itself divided on whether prolonged incarceration should override statutory bail restrictions.",
    source: "The Hindu",
    url: "https://www.thehindu.com",
    category: "courts",
    lean: "center",
    date: "2026-07-03"
  },
  {
    headline: "US pulling back from Indo-Pacific — and India, Japan, Australia are moving to fill the space",
    blurb: "As the Trump administration reduces its strategic footprint in the region, analysts say the Quad nations are quietly expanding cooperation to preserve the balance of power in the absence of American leadership.",
    source: "Indian Express",
    url: "https://indianexpress.com",
    category: "world",
    lean: "center",
    date: "2026-07-03"
  },
  {
  headline: "Modi-Takaichi summit produces 16 outcomes — semiconductors, energy, critical minerals on the table",
  blurb: "Japanese PM Sanae Takaichi's official visit to India yielded a joint declaration on economic security covering AI, clean energy, batteries and supply chain resilience. Both countries mark 75 years of diplomatic ties.",
  source: "OpIndia",
  url: "https://www.opindia.com/news-updates/india-japan-summit-meeting-between-pm-modi-and-pm-takaichi-results-in-16-outcomes/",
  category: "world",
  lean: "right",
  date: "2026-07-02"
},
{
  headline: "₹2.38 lakh crore defence proposals cleared — S-400 systems and transport aircraft among the big-ticket items",
  blurb: "The Defence Acquisition Council gave the nod to a major package of proposals aimed at strengthening India's air defence and surveillance capabilities amid ongoing regional tensions.",
  source: "Swarajya",
  url: "https://swarajyamag.com/topic/india",
  category: "defence",
  lean: "right",
  date: "2026-07-02"
},
{
  headline: "300 railway projects spanning 13,808 km sanctioned under PM Gati Shakti since FY23",
  blurb: "The Centre says the National Master Plan has driven a significant expansion of rail infrastructure across the country over the past three years, framing it as a backbone of the broader logistics modernisation push.",
  source: "Swarajya",
  url: "https://swarajyamag.com/topic/india",
  category: "economy",
  lean: "right",
  date: "2026-07-02"
},
{
  headline: "Modi chairs emergency meeting with states on fuel security as West Asia crisis drives oil price surge",
  blurb: "With crude prices climbing amid the ongoing West Asia conflict, the PM convened a high-level meeting to coordinate supply chain responses and strategic stockpiling plans with state governments.",
  source: "Swarajya",
  url: "https://swarajyamag.com/topic/india",
  category: "national",
  lean: "right",
  date: "2026-07-02"
},
{
  headline: "Guardian's Modi-Seychelles narrative doesn't hold up — the 'Blue Horizon' award is about local politics, not India",
  blurb: "OpIndia pushes back on a Guardian report framing a Seychelles diplomatic distinction as Modi-linked, arguing the award stems from internal Seychelles political restructuring and has nothing to do with the Indian PM.",
  source: "OpIndia",
  url: "https://www.opindia.com",
  category: "world",
  lean: "right",
  date: "2026-07-04"
},
{
  headline: "India reimposes windfall tax on aviation fuel and diesel exports as oil prices spike",
  blurb: "The government brought back the levy as West Asia tensions pushed up crude prices, aiming to curb exports and protect domestic fuel availability ahead of the monsoon season.",
  source: "Swarajya",
  url: "https://swarajyamag.com/topic/india",
  category: "economy",
  lean: "right",
  date: "2026-07-01"
},
  {
    headline: "US Supreme Court birthright citizenship ruling: less change for Indians than headlines suggest",
    blurb: "Despite the noise, legal experts say the ruling's practical impact on Indian immigrants and their children is narrower than initial reporting indicated — the pathways most Indians use remain intact.",
    source: "Indian Express",
    url: "https://indianexpress.com",
    category: "world",
    lean: "center",
    date: "2026-07-03"
  },
  {
    headline: "New EPF and EPS schemes notified — 270 million workers affected by the overhaul",
    blurb: "The government has replaced the 1952 and 1995 provident fund frameworks with updated schemes aligned to the Code on Social Security. PF balances, UANs and past contributions remain protected, but the administrative structure changes significantly.",
    source: "The Hindu",
    url: "https://www.thehindu.com",
    category: "economy",
    lean: "center",
    date: "2026-07-03"
  },

  // ── 2 JULY 2026 ──────────────────────────────────────────

  {
    headline: "Outlook: BJP now within reach of two-thirds majority — but the path runs through the DMK",
    blurb: "Through a combination of election wins, defections, and shifting alliances, the NDA is inching toward a supermajority in both houses. Whether the DMK abstains or opposes on a revised Delimitation Bill could determine whether it gets there.",
    source: "Outlook India",
    url: "https://www.outlookindia.com",
    category: "national",
    lean: "center",
    date: "2026-07-02"
  },
  {
    headline: "Congress argues the Delimitation Bill is not about women — it's about redrawing the map of power",
    blurb: "Rahul Gandhi told Parliament the 131st Amendment was a backdoor attempt to rewrite constituency boundaries in the BJP's favour, hidden behind the language of women's reservation. The bill was defeated in April but is widely expected to return.",
    source: "Indian National Congress",
    url: "https://inc.in",
    category: "national",
    lean: "left",
    date: "2026-07-02"
  },
  {
    headline: "The Print: INDIA bloc is fracturing — and BJP is the quiet beneficiary",
    blurb: "Regional parties drifting away from the opposition coalition, combined with TMC's declining clout in Bengal, is reducing the bloc's ability to mount a unified resistance to BJP's constitutional agenda.",
    source: "ThePrint",
    url: "https://theprint.in",
    category: "national",
    lean: "center",
    date: "2026-07-02"
  },
  {
    headline: "India reduced to a spectator as Iran tensions ease — but analysts warn it was always going to",
    blurb: "A reduction in US-Iran tensions gives India more room to balance its relationships in the Gulf, but also exposes how little control New Delhi has over the geopolitical forces that most affect its energy security.",
    source: "Outlook India",
    url: "https://www.outlookindia.com",
    category: "world",
    lean: "center",
    date: "2026-07-02"
  },
  {
    headline: "Air pollution plans need political will, not election-cycle optics",
    blurb: "An editorial argues that India's repeated air quality targets have consistently been subordinated to electoral calculus, with clean air promises peaking before votes and disappearing after them.",
    source: "The Hindu",
    url: "https://www.thehindu.com",
    category: "opinion",
    lean: "center",
    date: "2026-07-02"
  },
  {
    headline: "New telecom rules notified — India formally buries the colonial-era Telegraph Act of 1885",
    blurb: "The Telecommunications Act 2023's authorisation frameworks are now in force, replacing legislation that had governed Indian communications since the British Raj. Critics want to know what the new surveillance and interception powers actually look like in practice.",
    source: "Business Standard",
    url: "https://www.business-standard.com",
    category: "national",
    lean: "center",
    date: "2026-07-02"
  },

  // ── RECENT MAJOR STORIES (June–July 2026) ─────────────────

  {
    headline: "Shubhanshu Shukla's memoir lands a year after his ISS mission — and the political symbolism is unmistakable",
    blurb: "The first Indian to visit the International Space Station has published 'The Second Orbit', released exactly one year after launch. The book lands as ISRO ramps up for the Gaganyaan crewed mission, and the government is keen to make space a national pride story.",
    source: "Akashvani News",
    url: "https://newsonair.gov.in",
    category: "national",
    lean: "state-run",
    date: "2026-06-30"
  },
  {
    headline: "131st Amendment falls short in Lok Sabha — what happens to women's reservation now?",
    blurb: "The government's Delimitation Bill failed to get the required two-thirds majority in April, winning 298 votes against the 352 needed. The defeat has left women's reservation — which was bundled into the same package — in limbo, with both sides blaming each other.",
    source: "ThePrint",
    url: "https://theprint.in",
    category: "national",
    lean: "center",
    date: "2026-06-28"
  },
  {
    headline: "BJP wins West Bengal in a landslide — Mamata Banerjee's 15-year run ends",
    blurb: "Suvendu Adhikari was sworn in as Chief Minister after the BJP's historic majority in the April-May assembly elections, ending Trinamool Congress's dominance of the state. The Election Commission's controversial revision of electoral rolls before the vote remains contested.",
    source: "Hindustan Times",
    url: "https://www.hindustantimes.com",
    category: "states",
    lean: "center",
    date: "2026-06-25"
  },
  {
    headline: "Actor-turned-politician Vijay takes oath as Tamil Nadu's Chief Minister",
    blurb: "The film star's political debut ended with him heading the state government after the May election results. How he governs — and whether he can hold his own against both the DMK and BJP at the national level — is the question Tamil Nadu is watching.",
    source: "Indian Express",
    url: "https://indianexpress.com",
    category: "states",
    lean: "center",
    date: "2026-06-20"
  },
  {
    headline: "Supreme Court grants bail to two Delhi riot accused after years of pre-trial detention under UAPA",
    blurb: "Khalid Saifi and Tasleem Ahmad walked out on interim bail in May after the court raised concerns about how long they had been held without trial. A larger constitutional bench has been asked to rule on whether prolonged imprisonment can override UAPA's strict bail conditions.",
    source: "The Wire",
    url: "https://thewire.in",
    category: "courts",
    lean: "left",
    date: "2026-06-15"
  },
  {
    headline: "India-EU Free Trade Agreement signed — what it means for Indian workers and exporters",
    blurb: "After years of negotiations, India and the EU finalised a trade deal that opens European markets to Indian goods. Business groups are cautiously optimistic; labour rights organisations want to know what environmental and worker-protection clauses actually made the cut.",
    source: "Business Standard",
    url: "https://www.business-standard.com",
    category: "economy",
    lean: "center",
    date: "2026-06-10"
  },
  {
    headline: "Naxalite insurgency declared over — home minister says the last fighters have surrendered or been neutralised",
    blurb: "Amit Shah announced in March that the decades-long left-wing insurgency in central India had effectively ended after intensified security operations. Affected communities and civil society groups say the political and economic conditions that fuelled the movement remain unaddressed.",
    source: "NDTV",
    url: "https://www.ndtv.com",
    category: "national",
    lean: "center",
    date: "2026-06-01"
  },
  {
    headline: "NEET-UG 2026 cancelled after question paper leak — 1.8 million students face re-exam",
    blurb: "The National Testing Agency ordered a full cancellation of this year's medical entrance exam after a paper leak was confirmed. It is the second consecutive year the exam has been compromised, reigniting the debate about whether a single high-stakes national test can even be administered securely at this scale.",
    source: "India Today",
    url: "https://www.indiatoday.in",
    category: "national",
    lean: "center",
    date: "2026-05-20"
  },
  {
    headline: "Dutch PM raises press freedom and minority rights concerns before meeting Modi — India dismisses it",
    blurb: "Before bilateral talks in The Hague, Dutch PM Rob Jetten publicly flagged concerns about developments under the BJP government. The Indian side called it a lack of understanding. The exchange was barely covered in Indian mainstream media.",
    source: "The Wire",
    url: "https://thewire.in",
    category: "world",
    lean: "left",
    date: "2026-05-15"
  },
  {
    headline: "Nitin Nabin becomes BJP president — at 38, the youngest ever to hold the post",
    blurb: "The five-time Bihar MLA was elected unopposed in January, with Modi skipping over an entire generation of BJP veterans to appoint him. The opposition is still trying to figure out who he is. The BJP says that's the point.",
    source: "Mint",
    url: "https://www.livemint.com",
    category: "national",
    lean: "center",
    date: "2026-05-01"
  }

];
